defmodule Emerge.HostResolver do
  @moduledoc """
  Compatibility shim for `Emerge.Platform.HostResolver`.

  New target bootstraps generated by `:emerge_platform` start
  `Emerge.Platform.HostResolver`, which owns the mobile/native `inet_gethost`
  replacement boundary. This module remains for older apps that still start
  `Emerge.HostResolver` directly and for environments that only depend on
  `:emerge`.

  When `Emerge.Platform.HostResolver` is available it delegates to that module.
  Otherwise it falls back to the legacy in-repo implementation so existing apps
  keep working.
  """

  use GenServer

  @name :emerge_host_resolver

  @doc """
  Start the compatibility host resolver.
  """
  @spec start_link(keyword()) :: GenServer.on_start()
  def start_link(opts \\ []) do
    if platform_host_resolver_available?() do
      apply(Emerge.Platform.HostResolver, :start_link, [opts])
    else
      GenServer.start_link(__MODULE__, :ok, Keyword.merge(opts, name: @name))
    end
  end

  @impl true
  def init(:ok) do
    {:ok, %{}}
  end

  @impl true
  def handle_info({from, ref, {:resolve, name, proto_code}}, state) do
    result = do_resolve(name, proto_code)
    send(from, {ref, result})
    {:noreply, state}
  end

  def handle_info({from, ref, {:resolve_by_addr, addr_tuple, proto_code}}, state) do
    result = do_reverse_resolve(addr_tuple, proto_code)
    send(from, {ref, result})
    {:noreply, state}
  end

  defp do_resolve(name, proto_code) do
    try do
      case EmergeSkia.resolve_host(name, family(proto_code)) do
        {:ok, ips} -> {:ok, ips}
        {:error, _reason} -> {:error, :nxdomain}
      end
    rescue
      _ -> {:error, :nxdomain}
    end
  end

  defp do_reverse_resolve(_addr_tuple, _proto_code) do
    {:error, :nxdomain}
  end

  defp platform_host_resolver_available? do
    Code.ensure_loaded?(Emerge.Platform.HostResolver) and
      function_exported?(Emerge.Platform.HostResolver, :start_link, 1)
  end

  defp family(1), do: :inet
  defp family(2), do: :inet6
end
